export const queueConfig = {
    enabled: false,
    default_prio: 10, // Should be higher than any other priority
    priority: {
        "group.fullaccess": 1,
        "staff": 2,
        "dephead": 3,
        "civmanager": 3,
        "dev": 4,
        "leo": 5,
        "hcfr": 5,
        "certplus": 5,
        "certciv": 5,
        "leodono": 6,
        "commondono": 6,
        "sportsdono": 6,
        "offroaddono": 6,
        "superdono": 6,
        "civdono": 6,
        "group.personal": 6,
        "fulldono": 6,
    },
    adaptiveCard: {
        "card_title_isVisible": true,
        "card_title": "Welcome to Sunshine State Roleplay!",
        "card_header": "https://media.discordapp.net/attachments/562656258415525898/965286589532102716/unknown.png?ex=659ad031&is=65885b31&hm=fb6f042c0c6a9da44e4e0df421d9e055a578203e4061a4edf976a41e798256a7&=&format=webp&quality=lossless&width=1289&height=725",
        "card_description": "While you wait, join our Discord, read through our rules, and check our website!",
        "button1_title": "Discord",
        "button1_url": "https://discord.gg/ssrp",
        "button1_iconUrl": "https://cdn.iconscout.com/icon/free/png-512/free-discord-3770900-3147482.png?f=webp&w=256",
        "button2_title": "Rules",
        "button2_url": "https://docs.google.com/document/d/1dxC8MUo0kQt_I4IAcAWXnXFgMzGsH29ol8qlJ5LTfJ8/",
        "button2_iconUrl": "https://cdn.iconscout.com/icon/free/png-512/free-law-23-433279.png?f=webp&w=256",
        "button3_title": "Website",
        "button3_url": "https://sunshinestaterp.org",
        "button3_iconUrl": "https://cdn.iconscout.com/icon/free/png-512/free-website-3352014-2791479.png?f=webp&w=256",
    },
    "settings": {
        "debug": false,
        "noDiscordRejectMsg": "We could not find your Discord ID, please make sure Discord is running and that you're logged in." ,
        "graceListTime": 5,
        "maxPlayers": 64,
    }
}