// You can use both permissions based on categories and roles
// Inheritance is enabled by default

// Inhertiance can also pull from other inheritance groups.
// For this to work, you must have the other inheritance group defined first.
export const Groups = {
    "leo": [
        "weapon_bullpupshotgun",
		"weapon_combatshotgun",
		"weapon_flaregun",
		"weapon_vintagepistol",
		"weapon_pistol_mk2",
		"weapon_heavyshotgun",
		"weapon_fm41",
		"weapon_fm42",
		"weapon_x19",
		"weapon_carbinerifle",
		"weapon_flare", 
    ],
    "hcfr": [
        "weapon_flaregun",
		"weapon_flare",
    ],
    "swat": [
		"weapon_smg_mk2",
        "weapon_pumpshotgun_mk2",
		"weapon_assaultrifle_mk2",
		"weapon_carbinerifle_mk2",
		"weapon_specialcarbine_mk2",
		"weapon_bullpuprifle_mk2",
		"weapon_flashbang",
		"weapon_bzgas",
		"weapon_fm1_hk416",
		"weapon_fm2_hk416",
    ],
    "marksman": [
        "weapon_sniperrifle",
		"weapon_heavysniper",
		"weapon_marksmanrifle",
		"weapon_heavysniper_mk2",
		"weapon_marksmanrifle_mk2",
		"weapon_precisionrifle",
		"weapon_fm1_remington700",
		"weapon_fm2_remington700",
		"weapon_fm3_remington700",
		"weapon_fm4_remington700",
    ],
	"regciv": [
		"weapon_combatpistol",
		"weapon_snspistol",
		"weapon_pistolxm3",
		"weapon_pumpshotgun",
		"weapon_sawnoffshotgun",
	],
	"member": [
		"weapon_pistol",
	],
	"civsupervisor": [
		"weapon_precisionrifle",
		"weapon_sniperrifle",
		"weapon_marksmanrifle",
		"weapon_musket",
	],
	"certciv": [
		"weapon_flaregun",
		"weapon_assaultrifle",
		"weapon_compactrifle",
		"weapon_advancedrifle",
		"weapon_specialcarbine",
		"weapon_bullpuprifle",
		"weapon_militaryrifle",
		"weapon_heavyrifle",
		"weapon_tacticalrifle",
		"weapon_pistol50",
		"weapon_heavypistol",
		"weapon_combatpdw",
		"weapon_machinepistol",
		"weapon_tecpistol",
		"weapon_assaultsmg",
		"weapon_minismg",
		"weapon_dbshotgun",
		"weapon_gusenberg",
		"weapon_appistol",
		"weapon_microsmg",
		"weapon_smg",
		"weapon_candycane",
		"weapon_stungun",
		"weapon_stungun_mp",
		"weapon_battlerifle",
		"weapon_flare",
	],
    "group.fullaccess": [
        "weapon_grenadelauncher",
		"weapon_rpg",
		"weapon_compactlauncher",
		"weapon_hominglauncher",
		"weapon_firework",
		"weapon_railgun",
		"weapon_railgunxm3",
		"weapon_minigun",
		"weapon_grenadelauncher_smoke",
		"weapon_rayminigun",
		"weapon_emplauncher",
		"weapon_grenade",
		"weapon_stickybomb",
		"weapon_proxmine",
		"weapon_stinger",
		"weapon_passenger_rocket",
		"weapon_airstrike_rocket",
		"weapon_vehicle_rocket",
		"weapon_smokegrenade",
		"weapon_assaultshotgun",
		"weapon_raycarbine",
		"weapon_raypistol",
		"weapon_combatmg_mk2",
		"weapon_combatmg",
		"weapon_mg",
		"weapon_autoshotgun",
		"weapon_pipebomb",
		"weapon_molotov",
		"weapon_navyrevolver",
		"weapon_doubleaction",
		"weapon_revolver_mk2",
		"weapon_revolver",
		"weapon_marksmanpistol",
		"weapon_snowlauncher",
		"weapon_gadgetpistol",
    ],
	"certplus": [
		"",
	],
}

export const Inheritances = {
    "regciv": ["member"],
	"certciv": ["regciv"],
	"certplus": ["certciv"],
	"civmanager": ["certplus", "civsupervisor"],
	"leo": ["certciv"],
	"group.fullaccess": ["swat", "leo", "marksman", "hcfr", "civmanager"],
}